---
title: "Figure2cDRC"
output: html_notebook
---

Loading data:
```{r}
library(dplyr)
library(ggplot2)
library(ggthemes)
library(gridExtra)
library(lme4)
library(MASS)
library(drc)
#embryo heart rate
eheartdata<- read.csv("/Users/jreyn/OneDrive/Documents/grad school/NAFHM19/Data/analysis/EmbryoHeartbeat.csv")
eheartdata$Rep<- as.factor(eheartdata$Rep)
eheartdata
```

## Fitting an extended logistic regression model

lburst.m1<- drm(Bursts ~ Treatment, , data=postdata, fct=LL.4())
summary(lburst.m1)

```{r}
eheart.m1<- drm(Avg.Heartbeat ~ ï..Treatment,  data=eheartdata, fct=LL.3())
summary(eheart.m1)
```


```{r}
plot(eheart.m1)
```
```{r}
bmd(eheart.m1, 0.1, def=c("relative"), interval = c("delta"), display = TRUE)

```

Estimating LC5, LC10, LC50, with CI using delta method:
```{r}
ED(eheart.m1, c(5, 10, 50), interval = "delta")
```
Plotting with ggplot:
```{r}
newdata <- expand.grid(Treatment=exp(seq(log(0.5), log(45), length=45)))
```

```{r}
# predictions and confidence intervals
pm <- predict(eheart.m1, newdata=newdata, interval="confidence")
```

```{r}
# new data with predictions
newdata$p <- pm[,1]
newdata$pmin <- pm[,2]
newdata$pmax <- pm[,3]
```

```{r}
# plot curve
# need to shift conc == 0 a bit up, otherwise there are problems with coord_trans
eheartdata$Treatment0 <- eheartdata$ï..Treatment
eheartdata$Treatment0[eheartdata$Treatment0 == 0] <- 0.5
```


```{r}
# plotting the curve
ggplot(eheartdata, aes(x = Treatment0, y = Avg.Heartbeat)) +
geom_point() + 
geom_ribbon(data=newdata, aes(x=Treatment, y=p, ymin=pmin, ymax=pmax), alpha=0.2) +
geom_line(data=newdata, aes(x=Treatment, y=p)) +
coord_trans(x="log") +
xlab("NAFC concentration (mg/L)") + ylab("Average heartbeat per min") + theme_few()
```










