---
title: "Figure 4bDRC"
output: html_notebook
---
 
```{r}
library(dplyr)
library(ggplot2)
library(ggthemes)
library(gridExtra)
library(lme4)
library(MASS)
library(drc)

lburstdata<- read.csv("/Users/jreyn/OneDrive/Documents/grad school/NAFHM19/Data/analysis/behavsimple.csv")
lburstdata$Rep<- as.factor(lburstdata$Rep)
lburstdata$Video<- as.factor(lburstdata$Video)
lburstdata
```
Separating data into pre and post food addition:
```{r}
predata<- lburstdata[lburstdata$Feeding == 'Pre', ]
predata
  
postdata<- lburstdata[lburstdata$Feeding == 'Post', ]
postdata
```

## Fitting an extended logistic regression model
## upper limit should not be fixed, data is not binomial

ryegrass.LL.4 <- drm(rootl ~ conc, data = ryegrass, fct = LL.3())

```{r}
lburst.m1<- drm(Bursts ~ Treatment, data=postdata, fct=LL.3())
summary(lburst.m1)
```

```{r}
plot(lburst.m1)
```

BMD at 10%:
```{r}
bmd(lburst.m1, 0.1, def=c("relative"), interval = c("delta"), display = TRUE)
```

Estimating LC5, LC10, LC50, with CI using delta method:
```{r}
ED(lburst.m1, c(5, 10, 50), interval = "delta")
```



Plotting with ggplot:
```{r}
newdata <- expand.grid(Treatment=exp(seq(log(0.5), log(22), length=22)))
```

```{r}
# predictions and confidence intervals
pm <- predict(lburst.m1, newdata=newdata, interval="confidence")
```

```{r}
# new data with predictions
newdata$p <- pm[,1]
newdata$pmin <- pm[,2]
newdata$pmax <- pm[,3]
```

```{r}
# plot curve
# need to shift conc == 0 a bit up, otherwise there are problems with coord_trans
postdata$Treatment0 <- postdata$Treatment
postdata$Treatment0[postdata$Treatment0 == 0] <- 0.5
```

```{r}
# plotting the curve
ggplot(postdata, aes(x = Treatment0, y = Bursts)) +
geom_point() + 
geom_ribbon(data=newdata, aes(x=Treatment, y=p, ymin=pmin, ymax=pmax), alpha=0.2) +
geom_line(data=newdata, aes(x=Treatment, y=p)) +
coord_trans(x="log") +
xlab("NAFC concentration (mg/L)") + ylab("Number of burst events") + theme_few()
```





